name: "IKN Ibukota Nusantara"
author: "USERNAME"
description: "FiveM QBCore Server dengan Ox Inventory dan Mechanic Job"
version: 1.0

tasks:
  - action: "cloneRepository"
    data:
      url: "https://github.com/qbcore-framework/txAdminRecipe"
      branch: "main"

  - action: "configureDatabase"
    data:
      type: "mysql"
      host: "localhost"
      user: "root"
      password: "password"
      database: "fivem_database"

  - action: "installResources"
    data:
      resources:
        - "qb-core"
        - "oxmysql"
        - "ox_inventory"
        - "ox_target"
        - "qb-mechanic"
        - "mechanic_job"

  - action: "setupFiles"
    data:
      server.cfg: |
        endpoint_add_tcp "0.0.0.0:30120"
        endpoint_add_udp "0.0.0.0:30120"
        sv_licenseKey "GANTI_DENGAN_LICENSE_KEY_FIVEM_ANDA"
        set mysql_connection_string "mysql://root:password@localhost/fivem_database"
        exec resources.cfg

  - action: "startServer"




